version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - vetstore
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
  vetstore:
    image: vetstore:1.0.1
    ports:
      - "8080:8080"
    networks:
      - vetstore
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=postgres
      - PASSWORD=password
      - DATABASE=vetstore
      - JWT_SECRET=secret123
      - JWT_EXPIRATION=84600000
    depends_on:
      - postgres
networks:
  vetstore:
    driver: bridge